export const ActionType ={
    GET_USERS : "GET_USERS",
    ADD_USER : "ADD_USER",
    GET_SINGLE_USER : "GET_SINGLE_USER",
    UPDATE_USER : "UPDATE_USER",
    REMOVE_SELECTED_USER :"REMOVE_SELECTED_USER",
};   